# Generated by Django 6.0.4 on 2026-04-24 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('ICW', 'Information Commons West'), ('IC', 'Information Commons'), ('ICE', 'Information Commons East'), ('ITTC', 'Industry and Transportation Technology Center'), ('PMC', 'Plaster Manufacturing System'), ('LNC', 'Linconln Hall'), ('GRAFF', 'Graff Hall')], max_length=5)),
                ('room_num', models.CharField(max_length=5)),
                ('room_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('advisors', models.ManyToManyField(blank=True, related_name='faculty_advisor', to='account.profile')),
                ('members', models.ManyToManyField(blank=True, related_name='club_member', to='account.profile')),
                ('officers', models.ManyToManyField(blank=True, related_name='club_officer', to='account.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('point_value', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubhouse.club')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clubhouse.location')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.ManyToManyField(blank=True, related_name='rosters', to='account.profile')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='clubhouse.event')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('point_value', models.IntegerField(default=0)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='account.profile')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='clubhouse.event')),
            ],
            options={
                'unique_together': {('event', 'attendee')},
            },
        ),
    ]
