# Generated by Django 6.0.3 on 2026-04-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
