# Generated by Django 6.0.3 on 2026-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0002_club_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='emoji',
            field=models.CharField(blank=True, default='🏛️', max_length=10),
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='club_images/'),
        ),
    ]
