# Generated by Django 6.0.3 on 2026-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0003_club_emoji_club_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='pending_advisor_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='pending_advisor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
