# Generated by Django 6.0.3 on 2026-04-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0004_club_approved_club_pending_advisor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='denied',
            field=models.BooleanField(default=False),
        ),
    ]
