# Generated by Django 6.0.3 on 2026-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_image'),
        ('clubhouse', '0005_club_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='officer_applicants',
            field=models.ManyToManyField(blank=True, related_name='officer_applications', to='account.profile'),
        ),
    ]
