# Generated by Django 6.0.4 on 2026-04-24 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0007_event_token_attendance_delete_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
