# Generated by Django 6.0.3 on 2026-04-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0008_alter_event_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10),
        ),
    ]
