# Generated by Django 6.0.4 on 2026-04-25 03:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0009_event_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='point_value',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='rating',
        ),
        migrations.AddField(
            model_name='survey',
            name='bonus_points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='point_value',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='survey',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='clubhouse.event'),
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text Response'), ('STARS', 'Star Rating'), ('YESNO', 'Yes / No')], default='TEXT', max_length=5)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='clubhouse.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, default='')),
                ('int_answer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubhouse.surveyquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clubhouse.survey')),
            ],
        ),
    ]
