# Generated by Django 6.0.3 on 2026-04-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0010_remove_survey_point_value_remove_survey_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staffing_points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=10),
        ),
    ]
