# Generated by Django 6.0.3 on 2026-04-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubhouse', '0011_event_staffing_points_awarded_alter_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='token',
        ),
    ]
