# Generated by Django 6.0.4 on 2026-04-24 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
