# Generated by Django 6.0.4 on 2026-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0003_request_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='request',
            name='approval_status',
            field=models.CharField(choices=[('X', 'Denied'), ('O', 'Approved'), ('-', 'Pending')], default='-', max_length=1),
        ),
    ]
