# Generated by Django 6.0.4 on 2026-04-25 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0004_remove_request_is_approved_request_approval_status'),
        ('clubhouse', '0009_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='clubhouse.event'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('FINANCE', 'Finance'), ('CUSTODIAL', 'Custodial'), ('SECURITY', 'Security and Safety'), ('EVENT', 'Event Approval'), ('OTHER', 'See notes')], max_length=10),
        ),
    ]
