# Generated by Django 6.0.3 on 2026-04-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0005_request_event_alter_request_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
