# Generated by Django 6.0.4 on 2026-04-24 14:07

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otc_email', models.EmailField(max_length=254, unique=True, validators=[account.models.validate_otc_email])),
                ('points', models.IntegerField(default=0)),
                ('role', models.CharField(choices=[('ADMIN', 'Student Engagement'), ('ADVISOR', 'Faculty Advisor'), ('LEAD', 'Club Officer'), ('STUDENT', 'Student')], default='STUDENT', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
