# Generated by Django 6.0.4 on 2026-04-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_regenerate_short_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='checkin_token',
        ),
    ]
